/**
 * WebRTC 连麦功能常量定义
 */

// SRS 服务器配置
export const SRS_SERVER_URL = 'http://101.35.16.42:1985'
export const SRS_API_PATH = '/rtc/v1'

// 连接限制
export const MAX_PARTICIPANTS = 6

// 超时配置
export const CONNECTION_TIMEOUT = 10000 // 10 秒
export const REQUEST_TIMEOUT = 30000    // 30 秒
export const ICE_CANDIDATE_TIMEOUT = 5000 // 5 秒
export const SIGNALING_MESSAGE_TIMEOUT = 500 // 500 毫秒

// 重试配置
export const MAX_RETRY_ATTEMPTS = 3
export const INITIAL_RETRY_DELAY = 1000 // 1 秒
export const MAX_RETRY_DELAY = 10000    // 10 秒
export const RETRY_BACKOFF_MULTIPLIER = 2

// 网络质量阈值
export const PACKET_LOSS_THRESHOLD = 0.1  // 10%
export const RTT_THRESHOLD = 300          // 300ms
export const JITTER_THRESHOLD = 50        // 50ms

// 码率调整
export const BITRATE_REDUCTION_FACTOR = 0.25  // 降低 25%
export const LOW_BANDWIDTH_THRESHOLD = 500000 // 500 kbps

// 统计监控间隔
export const STATS_COLLECTION_INTERVAL = 2000 // 2 秒

// UI 响应时间
export const UI_RESPONSE_TIME = 100 // 100ms

// 状态更新时间
export const STATE_UPDATE_TIME = 100 // 100ms

// WebSocket 配置
export const WS_RECONNECT_INTERVAL = 1000 // 1 秒
export const HTTP_POLLING_INTERVAL = 1000 // 1 秒

// 错误代码
export const ERROR_CODES = {
  // 连接错误
  CONNECTION_FAILED: 'CONNECTION_FAILED',
  CONNECTION_TIMEOUT: 'CONNECTION_TIMEOUT',
  ICE_FAILED: 'ICE_FAILED',
  SERVER_UNREACHABLE: 'SERVER_UNREACHABLE',
  NETWORK_INTERRUPTED: 'NETWORK_INTERRUPTED',
  
  // 权限错误
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  
  // 信令错误
  SIGNALING_DISCONNECTED: 'SIGNALING_DISCONNECTED',
  MESSAGE_DELIVERY_FAILED: 'MESSAGE_DELIVERY_FAILED',
  INVALID_MESSAGE: 'INVALID_MESSAGE',
  AUTH_FAILED: 'AUTH_FAILED',
  
  // 状态错误
  INVALID_STATE: 'INVALID_STATE',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  CONNECTION_LIMIT_EXCEEDED: 'CONNECTION_LIMIT_EXCEEDED',
  
  // 媒体错误
  TRACK_ADD_FAILED: 'TRACK_ADD_FAILED',
  TRACK_REMOVE_FAILED: 'TRACK_REMOVE_FAILED',
  STREAM_CAPTURE_FAILED: 'STREAM_CAPTURE_FAILED',
  CODEC_NEGOTIATION_FAILED: 'CODEC_NEGOTIATION_FAILED'
} as const

// 错误消息
export const ERROR_MESSAGES = {
  [ERROR_CODES.CONNECTION_FAILED]: '连接失败，请检查网络后重试',
  [ERROR_CODES.CONNECTION_TIMEOUT]: '连接超时，请重试',
  [ERROR_CODES.ICE_FAILED]: 'ICE 连接失败',
  [ERROR_CODES.SERVER_UNREACHABLE]: '服务器无法访问，请稍后重试',
  [ERROR_CODES.NETWORK_INTERRUPTED]: '网络中断，正在尝试重新连接',
  [ERROR_CODES.PERMISSION_DENIED]: '需要麦克风/摄像头权限，请在浏览器设置中允许',
  [ERROR_CODES.DEVICE_NOT_FOUND]: '未找到音视频设备',
  [ERROR_CODES.SIGNALING_DISCONNECTED]: '信令连接断开',
  [ERROR_CODES.MESSAGE_DELIVERY_FAILED]: '消息发送失败',
  [ERROR_CODES.INVALID_MESSAGE]: '无效的消息格式',
  [ERROR_CODES.AUTH_FAILED]: '认证失败',
  [ERROR_CODES.INVALID_STATE]: '无效的状态转换',
  [ERROR_CODES.DUPLICATE_REQUEST]: '已有待处理的连麦请求',
  [ERROR_CODES.REQUEST_TIMEOUT]: '连麦请求超时',
  [ERROR_CODES.CONNECTION_LIMIT_EXCEEDED]: '连麦人数已达上限（最多 6 人）',
  [ERROR_CODES.TRACK_ADD_FAILED]: '添加音视频轨道失败',
  [ERROR_CODES.TRACK_REMOVE_FAILED]: '移除音视频轨道失败',
  [ERROR_CODES.STREAM_CAPTURE_FAILED]: '获取媒体流失败',
  [ERROR_CODES.CODEC_NEGOTIATION_FAILED]: '编解码器协商失败'
} as const
